spring:
  datasource:
    database1:
      url: jdbc:mysql://localhost:3306/yami_bbc?useUnicode=true&characterEncoding=utf8
      username: root
      password: 12345678
      driverClassName: com.mysql.jdbc.Driver
    database2:
      url: jdbc:mysql://localhost:3306/yami_bbc?useUnicode=true&characterEncoding=utf8
      username: root
      password: 12345678
      driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect